@startuml diagram

SelectiveSystem ..> Student
Behavior ..> Student
Training ..> Student
Student ..> Training
Couple ..> Student
Couple ..> Training


class Student {
    -id : long
    -behavior : Behavior
    -grades : unordered_map<string, int>
    -preferences : map<int, Training> 
    -has_training: bool
    +get_id() : long
    +get_behavior() : Behavior
    +get_grade(string id_grade) : int
    +get_preference(int order_preference) : Training
    +get_preferences() : map<int, Training> 
    +set_behavior(Behavior behavior) : void
    +push_grade(string id_grade, int grade) : void
    +remove_grade(int grade) : void
    +set_preference(int order_preference, Training training) : void
    +remove_preference(int order_preference) : void
    +switch_preferences(int order_pref_1, int order_pref_2) : void
    +remove_all_preferences() : void
    +get_has_training(): bool
    +set_has_training(bool status): void
}

class SelectiveSystem {
    -system_name : string
    -students: vector<Student>
    -trainings: vector<Training>
    + gale_shapley() : map<long, Couple> 
    + get_system_name() : string
    + add_student(Student student): void
    + add_training(Training training): void
    + remove_student(): void
    + remove_training(): void
    + clear_all(): void
}

class Training {
    - training_name : string
    - theme : string
    - location : string
    - ranking : int
    - has_student : bool
    - preferences : map<int, Student> 
    + get_name() : string
    + get_theme() : string
    + get_location() : string
    + get_ranking() : int
    + get_has_student: bool
    + get_preference(int order_preference) : Student
    + get_preferences() : map<int, Student> 
    + set_ranking(int ranking) : void
    + set_has_student(bool status): void
    + set_preference(int order_preference, Student student) : void
    + remove_preference(int order_preference) : void
    + switch_preferences(int order_pref_1, int order_pref_2) : void
    + remove_all_preferences() : void
}


class Behavior {
    -justified_absences : int
    -unjustified_absences : int
    -justified_delays : int
    -unjustified_delays : int
    -personal_issues : bool
    -detention_hours : int
    -reports : int
    -disciplinary_boards : int
    +get_justified_absences() : int
    +get_unjustified_absences() : int
    +get_justified_delays() : int
    +get_unjustified_delays() : int
    +get_personal_issues() : bool
    +get_detention_hours() : int
    +get_reports() : int
    +get_disciplinary_boards() : bool
    +set_justified_absences(int nb_justified_absences) : void
    +set_unjustified_absences(int nb_unjustified_absences) : void
    +set_justified_delays(int nb_justified_delays) : void
    +set_unjustified_delays(int nb_unjustified_delays) : void
    +set_personal_issues(bool has_issues) : void
    +set_detention_hours(int nb_detention_hours) : void
    +set_reports(int nb_reports) : void
    +set_disciplinary_boards(int nb_disciplinary_boards) : void
}

class Couple {
    -student : Student
    -training : Training
    + get_student() : Student
    + get_training() : Training
    + set_student(Student student) : void
    + set_training(Training training) : void
}


@enduml
